# Use Tomcat as the base image, since it can run .war files
# FROM tomcat:9.0-jdk17

# Remove default webapps (optional)
# RUN rm -rf /usr/local/tomcat/webapps/*

# Copy the WAR file to the Tomcat webapps directory
# ARG WAR_FILE=target/*.war
# COPY ${WAR_FILE} /usr/local/tomcat/webapps/ROOT.war
# COPY target/backend-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war
# COPY target/backend-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ExpenseWise.war

# Expose the default Tomcat port
# EXPOSE 8080

# Command to run Tomcat
# CMD ["catalina.sh", "run"]

# ENV DB_HOST=localhost
# ENV DB_PORT=3306
# ENV DB_NAME=expense
# ENV DB_USERNAME=root
# ENV DB_PASSWORD=''

FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /ExpenseWise

# Copy the JAR file into the container
COPY target/backend-0.0.1-SNAPSHOT.jar /ExpenseWise/backend.jar

EXPOSE 8080

# Run the JAR file
ENTRYPOINT ["java", "-jar", "backend.jar"]
